### ISSUE TITLE
Number of App Environment Variables

### ISSUE THREAD

**Issue by nicklester** [cfn-modules/fargate-service#27]
Hello,

Is there a reason for a hard limit of 6? My applications are beginning to need more as there is dynamic values being passed in from other cloud formation modules etc.. Would you accept a PR that brings this to 10? Or will I have to use a fork?

Many thanks

**Comment by michaelwittig** [comment]
Unfortunately, CloudFormation limits the number of parameters to 60. We use currently use 59. So you will not be able to extend the template any further. There is hope: With the new environment file feature we can get rid of all those parameters. Unfortunately, we have to wait for https://github.com/aws/aws-cli/issues/5479

**Comment by nicklester** [comment]
It is 60?  I thought we could only pass 6 environment variables in there params:

AppEnvironment1Key: '' # optional
AppEnvironment1Value: '' # optional

How do I use as many as 59?

Many thanks

**Comment by nicklester** [comment]
Ah sorry - Ive just realised that the number of parameters in the can template is 59. I may use my fork to remove some sidecar params for my purposes to extend the number of application params I can use until  #aws/aws-cli/issues/5479 becomes available.

**Comment by michaelwittig** [comment]
Lucky us: "You can now declare a maximum of 200 parameters in your AWS CloudFormation template." :)

**Comment by joshuahiggins** [comment]
A little confused here. The discussions here indicate that the repo at one point supported 60 env variables, but the current code only supports 20 (as of a few days ago). Would be great to support more than that. I'm having to fork my own module to add in support for more variables.

**Comment by michaelwittig** [comment]
@joshuahiggins When this issue was opened, CloudFormation supported a total of 60 parameters. We used 59 of the 60 parameters and supported AppEnvironment1 to AppEnvironment6. 

On 2020-1-22, CloudFormation increased the parameter limit to 200.

We went to AppEnvironment10 in December 2020 (see #7127d5b0e327cad797da08ac4eb7f5545a7d0864) and to AppEnvironment20 6 days ago 🥳  (see 24b1f8d78bc2ed1d99d7dba9218e8409763fabb7) 

I wonder why you would need more than 20?

**Comment by joshuahiggins** [comment]
@michaelwittig Gotcha, I understand the limit now. Since the topic was in the Fargate module and not the main repo, I assumed it was a limit that applied individually, not globally. But the limit impedes this module's ability because of how it passes configs from the parent down to the children, which makes more sense.

I don't think it matters why I need more than 20, when I do. But for what it's worth, I'm connecting a Docker instance to a number of configurable services. These services have anywhere from 1-5 environment variables aligned to them. For what it's worth, the Docker instance itself has over 50 configurable environment options. 

It sounds like forking is my only option here.

**Comment by michaelwittig** [comment]
I see. I was hoping for a lower number than 50...If you are fine with forking I would prefer this as a workaround.

I still hope that CloudFormation will release a feature in the future to help us solve the problem of passing complex types as parameters. We now have a [ToJsonString](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ToJsonString.html) function. Maybe they will add a FromJsonString...

**Comment by compuguy** [comment]
So does that mean one can just pass a Json file instead of having to use multiple environmental variables? That would be a bit cleaner than having to define as key value pairs. Because ECS and Fargate seem to support those types of file structures: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/taskdef-envfiles.html

**Comment by michaelwittig** [comment]
@compuguy in theory, yes: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-environmentfile.html

In practice, the [aws cloudformation package](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html) does not support the attribute and therefore we could only use this feature in this module by offering a parameter like `AppEnvironmentFileS3Arn` and the user of the module would need to upload the file on her own.
